### PR TITLE
Fixed C and Java Logos

### LINKED ISSUE #65: Fix the programming languages logos
- [x] I checked to make sure that this issue has not already been filed.

- [ ] I'm reporting the issue to the correct repository (for multi-repository projects) **(optional)**

# Expected Behavior:

Better logos for programming languages on languages page.

# Current Behavior:

What is the current behavior?
The C language logo has an unwanted background and is not clear, the Java logo is missing 
Screenshot (272)

# Solution:

Change the background images of logos

# Screenshots (optional):

### PR DESCRIPTION
**Pull request by supzi-del**
# Description

Changed the links of the logos of C and Java.

Fixed #65 

## Type of change

Please check options that are relevant to your PR.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have pulled the latest changes in the repository
- [ ] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

File: src/Data/Languages.js [hunk 1]
```diff
@@ -92,7 +92,7 @@ let languages = [
   {
```
Comment (shriya030) [inline src/Data/Languages.js:91]: Put , (comma) at line 91 after }

**Review by shriya030 — CHANGES_REQUESTED** [review]

**Review by aj3011 — APPROVED** [review]

**Review by shriya030 — APPROVED** [review]
